config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :invitations, only: [:create, :destroy]
  resources :events
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :invitations
  has_many :attendees, through: :invitations, source: :user
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  scope :past, -> { where('event_date < ?', DateTime.current) }
  scope :upcoming, -> { where('event_date > ?', DateTime.current) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @invitation = Invitation.new
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_path, notice: 'Event created successfully'
    else
      render :new, alert: 'Error, the event was not created'       
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: 'Event edited successfully'
    else
      render :edit, alert: 'Error, the event was not edited'       
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, notice: 'Event deleted successfully'
  end

  private

  def event_params
    params.require(:event).permit(:title, :event_date, :location)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    @invitation = Invitation.new(params_with_username_to_id)

    if @invitation.save
      redirect_to root_path, notice: 'Yay! You joined the event.'
    else
      redirect_to root_path, alert: 'Error, the invitation was not sent'
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    redirect_to root_path, notice: 'You no longer attendee the event.'
  end

  private

  def invitation_params
    params.require(:invitation).permit(:event_id, :user_id)
  end

  def find_username_id(username)
    User.find_by('username = ?', username).id if User.exists?(['username LIKE ?', username])
  end

  def params_with_username_to_id
    parameters = invitation_params
    parameters['user_id'] = find_username_id(parameters['user_id'])
    parameters
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do | form | %>
  <% @event.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div>
    <%= form.label :event_date %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :submit %>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit your event</h1>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1>Private Events</h1>
<ol>
  <h2>Past Events</h2>
  <% @past_events.each do | event | %>
    <li>
      <%= event.title %> |
      <small><%= event.event_date %></small>
      <strong> Creator: </strong><%= link_to event.creator.username.capitalize, user_path(event.creator.id) %>(<%= event.creator.id %>)
      -> <small><%= link_to "See event", event_path(event) %></small>
    </li>
  <% end %>
</ol>
<ol>
  <h2>Upcoming Events</h2>
  <% @upcoming_events.each do | event | %>
    <li>
      <%= event.title %> |
      <small><%= event.event_date %></small>
      <strong> Creator: </strong><%= link_to event.creator.username.capitalize, user_path(event.creator.id) %>(<%= event.creator.id %>)
      -> <small><%= link_to "See event", event_path(event) %></small>
    </li>
  <% end %>
</ol>

app/views/events/new.html.erb
<%= form_with model: @event do | form | %>
  <% @event.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div>
    <%= form.label :event_date %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :submit %>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<ul>
  <li><strong> Date</strong><%= @event.event_date %>
  <li><strong> Location</strong><%= @event.location %>
</ul>
<h5>Guest's list:</h5>
<ol>
  <% @event.attendees.each do | attendee | %>
    <li><small><%= attendee.username %></small>
  <% end %>
</ol>
<% if user_signed_in? %>
  <% if current_user == @event.creator %>
    <%= form_with model: @invitation, url: "/invitations" do | form | %>
      <%= form.hidden_field :event_id, value: @event.id %>
      <%= form.label :user_id, "Username's guest to invite: "  %>
      <%= form.text_field :user_id %>
      <%= form.submit "Send invitation" %>
    <% end %>
    <%= link_to 'Edit this event', edit_event_path(@event) %>
    <%= link_to 'Delete this event', event_path(@event),
                                    method: :delete,
                                    data: { confirm: 'Are you sure you want to delete the event?' }  %>
  <% end %>
  <% if current_user.attended_events.include?(@event) %>
    <%= link_to 'Exit the event', invitation_path(@event.invitations.find { |invitation| invitation.event_id == @event.id }.id),
                                    method: :delete,
                                    data: { confirm: 'Are you sure you want to quit the event?' }  %>
  <% end %>
<% else %>
  <button disabled="disabled">You must sign in to join the event</button>
<% end %>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <hr><hr>
      <%= link_to "Inicio", root_path %>
      <% if user_signed_in? %>
        <%= link_to "New event", new_event_path %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        | <small>Welcome: </small><strong><%= link_to current_user.username, user_path(current_user) %></strong>
      <% else %>
        <%= link_to "Sign in to create an event", new_user_session_path %>
      <% end %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% past_events, upcoming_events = [], [] %>
<% @user.attended_events.each do | event | %>
  <% event.event_date < DateTime.current ? past_events << event.title : upcoming_events << event.title %>
<% end %>

<h1>Users#show</h1>
<h3>Past Events</h3>
  <ol>
    <% past_events.each do | event_title | %>
    <li><%= event_title %></li>  
    <% end %>
  </ol>
<h3>Upcoming Events</h3>
  <ol>
    <% upcoming_events.each do | event_title | %>
    <li><%= event_title %></li>  
    <% end %>
  </ol>